# Database
spring:
  application:
    name: property-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:property_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
  # JPA
  jpa:
    hibernate:
      ddl-auto : ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info
  endpoint:
    health:
      show-details: always

eureka:
  client:
    enabled: false

# Server
server:
  port: ${SERVER_PORT:8082}

# Logging
logging:
  level:
    com.realestate.auth: DEBUG

app:
  gateway:
    url: ${APP_GATEWAY_URL:http://localhost:8080}
  file:
    upload-dir: ${FILE_UPLOAD_DIR:uploads}
  search:
    default-page-size : 20
    max-page-size : 100
    popular-destinations-limit : 10
    similar-properties-limit : 6
  services:
    user-service-url: ${USER_SERVICE_URL:http://localhost:8081}

aws:
  s3:
    bucket-name: bucket-block-lsi
    region: eu-west-3
  access-key: AKIAQZ4VATP3LZU7RGRJ
  secret-key: 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
storage:
  type: s3