apiVersion: v1
kind: Service
metadata:
  name: block-chain
  namespace: projet-backend
  labels:
    app: block-chain
spec:
  type: ClusterIP
  selector:
    app: block-chain
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP