apiVersion: v1
kind: Service
metadata:
  name: blockchain-layer
  namespace: projet-backend
  labels:
    app: blockchain-layer
spec:
  type: ClusterIP
  selector:
    app: blockchain-layer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
