apiVersion: v1
kind: Service
metadata:
  name: ia-service
  namespace: projet-backend
  labels:
    app: ia-service
spec:
  type: ClusterIP
  selector:
    app: ia-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP