apiVersion: v1
kind: Service
metadata:
  name: property-service
  namespace: projet-backend
  labels:
    app: property-service
spec:
  type: ClusterIP
  selector:
    app: property-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
