apiVersion: v1
kind: Service
metadata:
  name: rent-chain
  namespace: projet-frontend
  labels:
    app: rent-chain
spec:
  type: ClusterIP
  selector:
    app: rent-chain
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP