apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: projet-backend
type: Opaque
data:
  DB_USERNAME: ZGJ1c2Vy
  DB_PASSWORD: ZGJwYXNz
  JWT_SECRET: cmVwbGFjZS1tZQ==
  RABBITMQ_PASSWORD: cmFiYml0

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: projet-backend
type: kubernetes.io/tls
data:
  tls.crt: Q0VSVF9QTEFDRUhPTERFUiA=
  tls.key: S0VZX1BBTElDRUhPTERFUiA=

