version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: user-postgres
    environment:
      POSTGRES_DB: global_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - user-net

  user-service:
    image: user-service:1.0        # image qu'on a build√©e
    container_name: user-app
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: global_db
      DB_USER: postgres
      DB_PASS: postgres
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - user-net

networks:
  user-net:
    driver: bridge